### ISSUE TITLE
Automate Running Tests

### ISSUE THREAD

**Issue by outofambit** [WebBluetoothCG/manual-tests#38]
Hi! My team at @bocoup is working on automating these bluetooth API tests for Chrome. We'd like to take a more general approach so other browsers can benefit from these tests once they have implemented the Web Bluetooth API. I want to outline our proposed approach here to get any preliminary feedback y'all might have.

### Browser agnostic implementation

- Implement a script for running the existing tests with [`tap`](https://node-tap.org/).
  - Takes command line arguments to specify
    - the bluetooth device name to connect to (by either a string for exact match or a regex) and
    - the browser environment to test under.
  - This script will iterate through the tests in this repo, wrapping them in a basic `tap` test script that asserts the test passed.
  - Prints the debug information currently shown at the bottom of the test pages.
  - All tests will be run serially
- An interface that mocks necessary browser-specific implementations to complete these tests automatedly. Where possible we'll write browser non-specific implementations.
  - Utility to initialize the driver 
  - Utility to create session/target
  - Utility to upload espruino code
  - Utility to run JS test code
  - Utility to teardown or reset session/target
  - Utility to shut down the driver

### Chrome-specific driver implementation

After this, we will proceed to implement the mocked utilities functionality for Chrome. This will primarily entail implementing the above utilities with `puppeteer`.

### Usage

```shellsession
$ cd run_tests/
$ npm install
$ npm run test -- --device [device name regex] --browser [browser name]
```

### Folder structure

```
/run_tests/
  index.js (cli file)
  package.json (dependencies needed to run automated test suite)
  test.js (wrapper for existing html tests)
  driver-mock.js (interface mock)
  shared/
    shared.js (shared utilities not specific to any browser)
  chrome/
    driver.js (chrome implementations)
    ... (other chrome implementation files)
```

## Questions for feedback

- Should we use TypeScript for the code written as part of this work? This adds some complexity, but is fairly small since currently no JavaScripst in the repo is run outside of a browser and there would be a clear division between TS and JS files in the folder structure.
- Should we use a different folder or path to contain the file structure outlined above? (for example `/scripts/run_tests/` instead of `/run_tests/`)

**Please let me know if there's anything I can further clarify!**

**Comment by outofambit** [comment]
cc @gsinafirooz @reillyeon in case you have any feedback! i'm going to get started on implementation here soon.

**Comment by scheib** [comment]
cc @nondebug
